"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mergeRouters = exports.publicProcedure = exports.router = exports.t = void 0;
const server_1 = require("@trpc/server");
const t = server_1.initTRPC.context().create();
exports.t = t;
const router = t.router;
exports.router = router;
const publicProcedure = t.procedure;
exports.publicProcedure = publicProcedure;
const mergeRouters = t.mergeRouters;
exports.mergeRouters = mergeRouters;
